[2023-11-02T12:03:00.539-0700] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: snowflake_automation_dag.create_table manual__2023-11-02T19:02:47.521888+00:00 [queued]>
[2023-11-02T12:03:00.545-0700] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: snowflake_automation_dag.create_table manual__2023-11-02T19:02:47.521888+00:00 [queued]>
[2023-11-02T12:03:00.545-0700] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-02T12:03:00.545-0700] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-02T12:03:00.545-0700] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-02T12:03:00.550-0700] {taskinstance.py:1300} INFO - Executing <Task(SnowflakeOperator): create_table> on 2023-11-02 19:02:47.521888+00:00
[2023-11-02T12:03:00.552-0700] {standard_task_runner.py:55} INFO - Started process 31452 to run task
[2023-11-02T12:03:00.555-0700] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'snowflake_automation_dag', 'create_table', 'manual__2023-11-02T19:02:47.521888+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/snowflake_airflow_dag.py', '--cfg-path', '/var/folders/jh/g6c8fm7j3x148qd22mrgmrsw0000gn/T/tmpc5y5ada2']
[2023-11-02T12:03:00.557-0700] {standard_task_runner.py:83} INFO - Job 96: Subtask create_table
[2023-11-02T12:03:00.594-0700] {task_command.py:388} INFO - Running <TaskInstance: snowflake_automation_dag.create_table manual__2023-11-02T19:02:47.521888+00:00 [running]> on host anishs-air.lan
[2023-11-02T12:03:00.617-0700] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=snowflake_automation_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-11-02T19:02:47.521888+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-02T19:02:47.521888+00:00
[2023-11-02T12:03:00.618-0700] {sql.py:254} INFO - Executing: 
            create  table if not exists source_table( emp_no int,emp_name text,salary int, hra int ,Dept text);
        
[2023-11-02T12:03:00.621-0700] {base.py:73} INFO - Using connection ID 'snowflake_conn' for task execution.
[2023-11-02T12:03:00.699-0700] {base.py:73} INFO - Using connection ID 'snowflake_conn' for task execution.
[2023-11-02T12:03:00.701-0700] {connection.py:334} INFO - Snowflake Connector for Python Version: 3.3.1, Python Version: 3.10.12, Platform: macOS-13.5.1-arm64-arm-64bit
[2023-11-02T12:03:00.701-0700] {connection.py:1103} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-11-02T12:03:00.701-0700] {connection.py:1113} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2023-11-02T12:03:00.702-0700] {connection.py:1121} INFO - Setting use_openssl_only mode to False
[2023-11-02T12:05:11.451-0700] {local_task_job.py:272} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-11-02T12:05:11.457-0700] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 31452. PIDs of all processes in the group: [31452]
[2023-11-02T12:05:11.457-0700] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 31452
[2023-11-02T12:06:11.482-0700] {process_utils.py:147} WARNING - process psutil.Process(pid=31452, name='Python', status='running', started='12:03:00') did not respond to SIGTERM. Trying SIGKILL
[2023-11-02T12:06:11.486-0700] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 31452
[2023-11-02T12:06:11.494-0700] {process_utils.py:79} INFO - Process psutil.Process(pid=31452, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='12:03:00') (31452) terminated with exit code Negsignal.SIGKILL
[2023-11-02T12:06:11.495-0700] {standard_task_runner.py:168} ERROR - Job 96 was killed before it finished (likely due to running out of memory)
