[2023-11-01T20:04:44.820-0700] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dbt_snowflake_dag.bookings_2_seed manual__2023-11-02T03:04:28.843503+00:00 [queued]>
[2023-11-01T20:04:44.825-0700] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dbt_snowflake_dag.bookings_2_seed manual__2023-11-02T03:04:28.843503+00:00 [queued]>
[2023-11-01T20:04:44.825-0700] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-01T20:04:44.825-0700] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-01T20:04:44.825-0700] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-01T20:04:44.829-0700] {taskinstance.py:1300} INFO - Executing <Task(DbtSeedLocalOperator): bookings_2_seed> on 2023-11-02 03:04:28.843503+00:00
[2023-11-01T20:04:44.831-0700] {standard_task_runner.py:55} INFO - Started process 97300 to run task
[2023-11-01T20:04:44.834-0700] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_snowflake_dag', 'bookings_2_seed', 'manual__2023-11-02T03:04:28.843503+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/dbt_airflow_snowflake.py', '--cfg-path', '/var/folders/jh/g6c8fm7j3x148qd22mrgmrsw0000gn/T/tmpb5cjr9ic']
[2023-11-01T20:04:44.835-0700] {standard_task_runner.py:83} INFO - Job 58: Subtask bookings_2_seed
[2023-11-01T20:04:44.851-0700] {task_command.py:388} INFO - Running <TaskInstance: dbt_snowflake_dag.bookings_2_seed manual__2023-11-02T03:04:28.843503+00:00 [running]> on host anishs-air.lan
[2023-11-01T20:04:44.868-0700] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt_snowflake_dag
AIRFLOW_CTX_TASK_ID=bookings_2_seed
AIRFLOW_CTX_EXECUTION_DATE=2023-11-02T03:04:28.843503+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-02T03:04:28.843503+00:00
[2023-11-01T20:04:44.869-0700] {local.py:194} INFO - Cloning project to writable temp directory /var/folders/jh/g6c8fm7j3x148qd22mrgmrsw0000gn/T/tmp13rjxd82 from /Users/anishmore/airflow/dbt/data_pipeline
[2023-11-01T20:04:44.918-0700] {subprocess.py:60} INFO - Tmp dir root location: 
 /var/folders/jh/g6c8fm7j3x148qd22mrgmrsw0000gn/T
[2023-11-01T20:04:44.919-0700] {subprocess.py:73} INFO - Running command: ['/opt/homebrew/bin/dbt', 'deps']
[2023-11-01T20:04:44.922-0700] {subprocess.py:84} INFO - Command output:
[2023-11-01T20:04:46.032-0700] {subprocess.py:94} INFO - [0m03:04:46  Running with dbt=1.6.7
[2023-11-01T20:04:46.361-0700] {subprocess.py:94} INFO - [0m03:04:46  Installing dbt-labs/dbt_utils
[2023-11-01T20:04:46.844-0700] {subprocess.py:94} INFO - [0m03:04:46  Installed from version 1.1.1
[2023-11-01T20:04:46.845-0700] {subprocess.py:94} INFO - [0m03:04:46  Up to date!
[2023-11-01T20:04:47.377-0700] {subprocess.py:98} INFO - Command exited with return code 0
[2023-11-01T20:04:47.397-0700] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/cosmos/operators/local.py", line 412, in execute
    self.build_and_run_cmd(context=context, cmd_flags=cmd_flags)
  File "/opt/homebrew/lib/python3.10/site-packages/cosmos/operators/local.py", line 361, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/opt/homebrew/lib/python3.10/site-packages/cosmos/operators/local.py", line 215, in run_command
    with self.profile_config.ensure_profile() as (profile_path, env_vars):
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/opt/homebrew/lib/python3.10/site-packages/cosmos/config.py", line 176, in ensure_profile
    profile_contents = self.profile_mapping.get_profile_file_contents(
  File "/opt/homebrew/lib/python3.10/site-packages/cosmos/profiles/base.py", line 146, in get_profile_file_contents
    profile_vars = self.profile
  File "/opt/homebrew/lib/python3.10/site-packages/cosmos/profiles/snowflake/user_privatekey.py", line 68, in profile
    **self.mapped_params,
  File "/opt/homebrew/lib/python3.10/site-packages/cosmos/profiles/base.py", line 209, in mapped_params
    mapped_params[dbt_field] = self.get_dbt_value(dbt_field)
  File "/opt/homebrew/lib/python3.10/site-packages/cosmos/profiles/base.py", line 182, in get_dbt_value
    value = self.conn.extra_dejson.get(airflow_field)
  File "/opt/homebrew/lib/python3.10/site-packages/cosmos/profiles/snowflake/user_privatekey.py", line 53, in conn
    conn = super().conn
  File "/opt/homebrew/lib/python3.10/site-packages/cosmos/profiles/base.py", line 49, in conn
    conn = BaseHook.get_connection(self.conn_id)
  File "/opt/homebrew/lib/python3.10/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/opt/homebrew/lib/python3.10/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2023-11-01T20:04:47.401-0700] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=dbt_snowflake_dag, task_id=bookings_2_seed, execution_date=20231102T030428, start_date=20231102T030444, end_date=20231102T030447
[2023-11-01T20:04:47.405-0700] {standard_task_runner.py:100} ERROR - Failed to execute job 58 for task bookings_2_seed (The conn_id `snowflake_conn` isn't defined; 97300)
[2023-11-01T20:04:47.435-0700] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-11-01T20:04:47.447-0700] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
